# Generated by Django 5.1.1 on 2024-09-10 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.TextField(),
        ),
    ]
