# Generated by Django 5.1.1 on 2024-09-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefas_responsavel_alter_tarefas_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='responsavel',
        ),
    ]
