# Generated by Django 5.1.1 on 2024-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tarefas_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Em andamento'), ('3', 'Concluída')], max_length=20),
        ),
    ]
